# 3. Important Functions

In [ ]:
df1

                  Name  ID  Gender  Salary  Age
Employee_ID
101            Utkarsh   1    Male  200000   38
102             Kartik   2    Male   80000   34
103          Aishwarya   3  Female   90000   34
104              Anand   4    Male   65000   42
105            Shalini   5  Female  150000   40
106             Pratik   6    Male   80000   45
107           Monalika   7  Female   70000   25
108             Ayesha   8  Female   60000   27
109              Anant   9    Male  100000   33
110          Shamiksha  10  Female   45000   40
111           Prashant  11    Male   55000   39
112             Mohini  12  Female   65000   37

In [ ]:
df1.loc[113] = df1.loc[109]
df1.loc[114] = df1.loc[110]
df1.loc[115] = ['Kavita', 15, np.nan, 85000, 30]
df1.loc[116] = ['Pratik', 16, np.nan, np.nan, 32]
df1

                  Name  ID  Gender    Salary  Age
Employee_ID
101            Utkarsh   1    Male  200000.0   38
102             Kartik   2    Male   80000.0   34
103          Aishwarya   3  Female   90000.0   34
104              Anand   4    Male   65000.0   42
105            Shalini   5  Female  150000.0   40
106             Pratik   6    Male   80000.0   45
107           Monalika   7  Female   70000.0   25
108             Ayesha   8  Female   60000.0   27
109              Anant   9    Male  100000.0   33
110          Shamiksha  10  Female   45000.0   40
111           Prashant  11    Male   55000.0   39
112             Mohini  12  Female   65000.0   37
113              Anant   9    Male  100000.0   33
114          Shamiksha  10  Female   45000.0   40
115             Kavita  15     NaN   85000.0   30
116             Pratik  16     NaN       NaN   32

In [ ]:
df1.head()

                  Name  ID  Gender    Salary  Age
Employee_ID
101            Utkarsh   1    Male  200000.0   38
102             Kartik   2    Male   80000.0   34
103          Aishwarya   3  Female   90000.0   34
104              Anand   4    Male   65000.0   42
105            Shalini   5  Female  150000.0   40

In [ ]:
df1.head(3)

                  Name  ID  Gender    Salary  Age
Employee_ID
101            Utkarsh   1    Male  200000.0   38
102             Kartik   2    Male   80000.0   34
103          Aishwarya   3  Female   90000.0   34

In [ ]:
df1.tail()

                  Name  ID  Gender    Salary  Age
Employee_ID
112             Mohini  12  Female   65000.0   37
113              Anant   9    Male  100000.0   33
114          Shamiksha  10  Female   45000.0   40
115             Kavita  15     NaN   85000.0   30
116             Pratik  16     NaN       NaN   32

In [ ]:
df1.tail(7)

                  Name  ID  Gender    Salary  Age
Employee_ID
110          Shamiksha  10  Female   45000.0   40
111           Prashant  11    Male   55000.0   39
112             Mohini  12  Female   65000.0   37
113              Anant   9    Male  100000.0   33
114          Shamiksha  10  Female   45000.0   40
115             Kavita  15     NaN   85000.0   30
116             Pratik  16     NaN       NaN   32

In [ ]:
df1

                  Name  ID  Gender    Salary  Age
Employee_ID
101            Utkarsh   1    Male  200000.0   38
102             Kartik   2    Male   80000.0   34
103          Aishwarya   3  Female   90000.0   34
104              Anand   4    Male   65000.0   42
105            Shalini   5  Female  150000.0   40
106             Pratik   6    Male   80000.0   45
107           Monalika   7  Female   70000.0   25
108             Ayesha   8  Female   60000.0   27
109              Anant   9    Male  100000.0   33
110          Shamiksha  10  Female   45000.0   40
111           Prashant  11    Male   55000.0   39
112             Mohini  12  Female   65000.0   37
113              Anant   9    Male  100000.0   33
114          Shamiksha  10  Female   45000.0   40
115             Kavita  15     NaN   85000.0   30
116             Pratik  16     NaN       NaN   32

In [ ]:
df1.isnull()

              Name     ID  Gender  Salary    Age
Employee_ID
101          False  False   False   False  False
102          False  False   False   False  False
103          False  False   False   False  False
104          False  False   False   False  False
105          False  False   False   False  False
106          False  False   False   False  False
107          False  False   False   False  False
108          False  False   False   False  False
109          False  False   False   False  False
110          False  False   False   False  False
111          False  False   False   False  False
112          False  False   False   False  False
113          False  False   False   False  False
114          False  False   False   False  False
115          False  False    True   False  False
116          False  False    True    True  False

In [ ]:
# Check for null values
df1.isnull().sum()

Name      0
ID        0
Gender    2
Salary    1
Age       0
dtype: int64

In [ ]:
df1.Salary.isnull()

Employee_ID
101    False
102    False
103    False
104    False
105    False
106    False
107    False
108    False
109    False
110    False
111    False
112    False
113    False
114    False
115    False
116     True
Name: Salary, dtype: bool

In [ ]:
df1.Salary.isnull().sum()

1

In [ ]:
df1.isna().sum()

Name      0
ID        0
Gender    2
Salary    1
Age       0
dtype: int64

In [ ]:
# Check for duplicates
df1.duplicated()

Employee_ID
101    False
102    False
103    False
104    False
105    False
106    False
107    False
108    False
109    False
110    False
111    False
112    False
113     True
114     True
115    False
116    False
dtype: bool

In [ ]:
df1.duplicated().sum()

2

In [ ]:
# To drop duplicate records
df1.drop_duplicates(inplace = True)
df1

                  Name  ID  Gender    Salary  Age
Employee_ID
101            Utkarsh   1    Male  200000.0   38
102             Kartik   2    Male   80000.0   34
103          Aishwarya   3  Female   90000.0   34
104              Anand   4    Male   65000.0   42
105            Shalini   5  Female  150000.0   40
106             Pratik   6    Male   80000.0   45
107           Monalika   7  Female   70000.0   25
108             Ayesha   8  Female   60000.0   27
109              Anant   9    Male  100000.0   33
110          Shamiksha  10  Female   45000.0   40
111           Prashant  11    Male   55000.0   39
112             Mohini  12  Female   65000.0   37
115             Kavita  15     NaN   85000.0   30
116             Pratik  16     NaN       NaN   32

In [ ]:
df1.nunique()          # Number of unique values

Name      13
ID        14
Gender     2
Salary    11
Age       12
dtype: int64

In [ ]:
df1['Salary'].nunique()

11

In [ ]:
df1['Name'].nunique()

13

In [ ]:
df1['Name'].unique()            # Gives unique values

array(['Utkarsh', 'Kartik', 'Aishwarya', 'Anand', 'Shalini', 'Pratik',
       'Monalika', 'Ayesha', 'Anant', 'Shamiksha', 'Prashant', 'Mohini',
       'Kavita'], dtype=object)

In [ ]:
df1['Gender'].unique()

array(['Male', 'Female', nan], dtype=object)

In [ ]:
df1['Gender'].dropna().unique()    # To avoid nan

array(['Male', 'Female'], dtype=object)

In [ ]:
df1.sort_index(ascending = False)

                  Name  ID  Gender    Salary  Age
Employee_ID
116             Pratik  16     NaN       NaN   32
115             Kavita  15     NaN   85000.0   30
112             Mohini  12  Female   65000.0   37
111           Prashant  11    Male   55000.0   39
110          Shamiksha  10  Female   45000.0   40
109              Anant   9    Male  100000.0   33
108             Ayesha   8  Female   60000.0   27
107           Monalika   7  Female   70000.0   25
106             Pratik   6    Male   80000.0   45
105            Shalini   5  Female  150000.0   40
104              Anand   4    Male   65000.0   42
103          Aishwarya   3  Female   90000.0   34
102             Kartik   2    Male   80000.0   34
101            Utkarsh   1    Male  200000.0   38

In [ ]:
df1.sort_index()

                  Name  ID  Gender    Salary  Age
Employee_ID
101            Utkarsh   1    Male  200000.0   38
102             Kartik   2    Male   80000.0   34
103          Aishwarya   3  Female   90000.0   34
104              Anand   4    Male   65000.0   42
105            Shalini   5  Female  150000.0   40
106             Pratik   6    Male   80000.0   45
107           Monalika   7  Female   70000.0   25
108             Ayesha   8  Female   60000.0   27
109              Anant   9    Male  100000.0   33
110          Shamiksha  10  Female   45000.0   40
111           Prashant  11    Male   55000.0   39
112             Mohini  12  Female   65000.0   37
115             Kavita  15     NaN   85000.0   30
116             Pratik  16     NaN       NaN   32

In [ ]:
df1.sort_values(by = 'Salary')   # Used to order the dataframe based on a column (or Columns)

                  Name  ID  Gender    Salary  Age
Employee_ID
110          Shamiksha  10  Female   45000.0   40
111           Prashant  11    Male   55000.0   39
108             Ayesha   8  Female   60000.0   27
104              Anand   4    Male   65000.0   42
112             Mohini  12  Female   65000.0   37
107           Monalika   7  Female   70000.0   25
102             Kartik   2    Male   80000.0   34
106             Pratik   6    Male   80000.0   45
115             Kavita  15     NaN   85000.0   30
103          Aishwarya   3  Female   90000.0   34
109              Anant   9    Male  100000.0   33
105            Shalini   5  Female  150000.0   40
101            Utkarsh   1    Male  200000.0   38
116             Pratik  16     NaN       NaN   32

In [ ]:
df1.sort_values(by = 'Salary', ascending = False)

                  Name  ID  Gender    Salary  Age
Employee_ID
101            Utkarsh   1    Male  200000.0   38
105            Shalini   5  Female  150000.0   40
109              Anant   9    Male  100000.0   33
103          Aishwarya   3  Female   90000.0   34
115             Kavita  15     NaN   85000.0   30
102             Kartik   2    Male   80000.0   34
106             Pratik   6    Male   80000.0   45
107           Monalika   7  Female   70000.0   25
104              Anand   4    Male   65000.0   42
112             Mohini  12  Female   65000.0   37
108             Ayesha   8  Female   60000.0   27
111           Prashant  11    Male   55000.0   39
110          Shamiksha  10  Female   45000.0   40
116             Pratik  16     NaN       NaN   32

In [ ]:
df1.sort_values(by = 'Name')

                  Name  ID  Gender    Salary  Age
Employee_ID
103          Aishwarya   3  Female   90000.0   34
104              Anand   4    Male   65000.0   42
109              Anant   9    Male  100000.0   33
108             Ayesha   8  Female   60000.0   27
102             Kartik   2    Male   80000.0   34
115             Kavita  15     NaN   85000.0   30
112             Mohini  12  Female   65000.0   37
107           Monalika   7  Female   70000.0   25
111           Prashant  11    Male   55000.0   39
106             Pratik   6    Male   80000.0   45
116             Pratik  16     NaN       NaN   32
105            Shalini   5  Female  150000.0   40
110          Shamiksha  10  Female   45000.0   40
101            Utkarsh   1    Male  200000.0   38

In [ ]:
df1.sort_values(by = ['Age', 'Salary'])

                  Name  ID  Gender    Salary  Age
Employee_ID
107           Monalika   7  Female   70000.0   25
108             Ayesha   8  Female   60000.0   27
115             Kavita  15     NaN   85000.0   30
116             Pratik  16     NaN       NaN   32
109              Anant   9    Male  100000.0   33
102             Kartik   2    Male   80000.0   34
103          Aishwarya   3  Female   90000.0   34
112             Mohini  12  Female   65000.0   37
101            Utkarsh   1    Male  200000.0   38
111           Prashant  11    Male   55000.0   39
110          Shamiksha  10  Female   45000.0   40
105            Shalini   5  Female  150000.0   40
104              Anand   4    Male   65000.0   42
106             Pratik   6    Male   80000.0   45

In [ ]:
pd.concat([df1,df1],axis = 0) # Rows

                  Name  ID  Gender    Salary  Age
Employee_ID
101            Utkarsh   1    Male  200000.0   38
102             Kartik   2    Male   80000.0   34
103          Aishwarya   3  Female   90000.0   34
104              Anand   4    Male   65000.0   42
105            Shalini   5  Female  150000.0   40
106             Pratik   6    Male   80000.0   45
107           Monalika   7  Female   70000.0   25
108             Ayesha   8  Female   60000.0   27
109              Anant   9    Male  100000.0   33
110          Shamiksha  10  Female   45000.0   40
111           Prashant  11    Male   55000.0   39
112             Mohini  12  Female   65000.0   37
115             Kavita  15     NaN   85000.0   30
116             Pratik  16     NaN       NaN   32
101            Utkarsh   1    Male  200000.0   38
102             Kartik   2    Male   80000.0   34
103          Aishwarya   3  Female   90000.0   34
104              Anand   4    Male   65000.0   42
105            Shalini   5  Female  150000.0   40
106             Pratik   6    Male   80000.0   45
107           Monalika   7  Female   70000.0   25
108             Ayesha   8  Female   60000.0   27
109              Anant   9    Male  100000.0   33
110          Shamiksha  10  Female   45000.0   40
111           Prashant  11    Male   55000.0   39
112             Mohini  12  Female   65000.0   37
115             Kavita  15     NaN   85000.0   30
116             Pratik  16     NaN       NaN   32

In [ ]:
pd.concat([df1,df1], axis = 1)

,Name,ID,Gender,Salary,Age,Name,ID,Gender,Salary,Age
Employee_ID,,,,,,,,,,
101,Utkarsh,1,Male,200000.0,38,Utkarsh,1,Male,200000.0,38
102,Kartik,2,Male,80000.0,34,Kartik,2,Male,80000.0,34
103,Aishwarya,3,Female,90000.0,34,Aishwarya,3,Female,90000.0,34
104,Anand,4,Male,65000.0,42,Anand,4,Male,65000.0,42
105,Shalini,5,Female,150000.0,40,Shalini,5,Female,150000.0,40
106,Pratik,6,Male,80000.0,45,Pratik,6,Male,80000.0,45
107,Monalika,7,Female,70000.0,25,Monalika,7,Female,70000.0,25
108,Ayesha,8,Female,60000.0,27,Ayesha,8,Female,60000.0,27
109,Anant,9,Male,100000.0,33,Anant,9,Male,100000.0,33
110,Shamiksha,10,Female,45000.0,40,Shamiksha,10,Female,45000.0,40
111,Prashant,11,Male,55000.0,39,Prashant,11,Male,55000.0,39
112,Mohini,12,Female,65000.0,37,Mohini,12,Female,65000.0,37
115,Kavita,15,NaN,85000.0,30,Kavita,15,NaN,85000.0,30
116,Pratik,16,NaN,NaN,32,Pratik,16,NaN,NaN,32

In [ ]:
df1.Salary.value_counts()    # It counts the values

Salary
80000.0     2
65000.0     2
200000.0    1
90000.0     1
150000.0    1
70000.0     1
60000.0     1
100000.0    1
45000.0     1
55000.0     1
85000.0     1
Name: count, dtype: int64

In [ ]:
df1.Gender.value_counts()

Gender
Male      6
Female    6
Name: count, dtype: int64

In [ ]:
df1.Gender.value_counts(normalize = True)  # To get ratios

Gender
Male      0.5
Female    0.5
Name: proportion, dtype: float64

In [ ]:
df1.describe()           # Gives descriptive statistics about numerical columns

              ID         Salary        Age
count  14.000000      13.000000  14.000000
mean    7.785714   88076.923077  35.428571
std     4.660448   42599.807391   5.747431
min     1.000000   45000.000000  25.000000
25%     4.250000   65000.000000  32.250000
50%     7.500000   80000.000000  35.500000
75%    10.750000   90000.000000  39.750000
max    16.000000  200000.000000  45.000000

In [ ]:
df1[['Age','Salary']].describe()

             Age         Salary
count  14.000000      13.000000
mean   35.428571   88076.923077
std     5.747431   42599.807391
min    25.000000   45000.000000
25%    32.250000   65000.000000
50%    35.500000   80000.000000
75%    39.750000   90000.000000
max    45.000000  200000.000000

In [ ]:
df1.count()

Name      14
ID        14
Gender    12
Salary    13
Age       14
dtype: int64

In [ ]:
df1.mean()

TypeError: Could not convert ['UtkarshKartikAishwaryaAnandShaliniPratikMonalikaAyeshaAnantShamikshaPrashantMohiniKavitaPratik'] to numeric

In [ ]:
# df1['Salary'].mean()
df1.Salary.mean()

88076.92307692308

In [ ]:
df1.var()

TypeError: could not convert string to float: 'Utkarsh'

In [ ]:
df1['Salary'].var()

In [ ]:
df1.std()

In [ ]:
df1['Salary'].std()

42599.80739092126

In [ ]:
df1.median()

TypeError: could not convert string to float: 'Utkarsh'

In [ ]:
df1['Salary'].median()

80000.0

In [ ]:
df1['Age'].mode()

0    34
1    40
Name: Age, dtype: int64

In [ ]:
df1.Age.value_counts()

Age
34    2
40    2
38    1
42    1
45    1
25    1
27    1
33    1
39    1
37    1
30    1
32    1
Name: count, dtype: int64

In [ ]:
df1['Age'].dropna().mode()     # Ignore nan values

0    34
1    40
Name: Age, dtype: int64

In [ ]:
df1.Age.quantile(0.25)

32.25

In [ ]:
df1.Age.median()

35.5

In [ ]:
df1.Age.quantile(0.5)

35.5

In [ ]:
df1.Age.quantile(0.75)

39.75

In [ ]:
df1['Salary'].apply(np.sqrt)

Employee_ID
101    447.213595
102    282.842712
103    300.000000
104    254.950976
105    387.298335
106    282.842712
107    264.575131
108    244.948974
109    316.227766
110    212.132034
111    234.520788
112    254.950976
115    291.547595
116           NaN
Name: Salary, dtype: float64

In [ ]:
df1

                  Name  ID  Gender    Salary  Age
Employee_ID
101            Utkarsh   1    Male  200000.0   38
102             Kartik   2    Male   80000.0   34
103          Aishwarya   3  Female   90000.0   34
104              Anand   4    Male   65000.0   42
105            Shalini   5  Female  150000.0   40
106             Pratik   6    Male   80000.0   45
107           Monalika   7  Female   70000.0   25
108             Ayesha   8  Female   60000.0   27
109              Anant   9    Male  100000.0   33
110          Shamiksha  10  Female   45000.0   40
111           Prashant  11    Male   55000.0   39
112             Mohini  12  Female   65000.0   37
115             Kavita  15     NaN   85000.0   30
116             Pratik  16     NaN       NaN   32

In [ ]:
df1['Salary'].apply(lambda num : 1.1 * num)

Employee_ID
101    220000.0
102     88000.0
103     99000.0
104     71500.0
105    165000.0
106     88000.0
107     77000.0
108     66000.0
109    110000.0
110     49500.0
111     60500.0
112     71500.0
115     93500.0
116         NaN
Name: Salary, dtype: float64

In [ ]:
df1.groupby(by = 'Gender')['Age'].mean()

Gender
Female    33.833333
Male      38.500000
Name: Age, dtype: float64

In [ ]:
df1.groupby(by = 'Gender')['Salary'].mean()

Gender
Female    80000.000000
Male      96666.666667
Name: Salary, dtype: float64

In [ ]:
df1.cov()       # Covariance

ValueError: could not convert string to float: 'Utkarsh'

In [ ]:
df1[['Age', 'Salary']].cov()

                 Age        Salary
Age        33.032967  3.435897e+04
Salary  34358.974359  1.814744e+09

In [ ]:
df1[['Age', 'Salary']].corr()    # Correlation

            Age   Salary
Age     1.00000  0.13686
Salary  0.13686  1.00000

# 4. Dealing With CSV Files

In [ ]:
data = pd.read_csv('/content/Automobile_data.csv')
data.head(10)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450
5,2,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.4,8.5,110,5500,19,25,15250
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.4,8.5,110,5500,19,25,17710
7,1,?,audi,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.4,8.5,110,5500,19,25,18920
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.4,8.3,140,5500,17,20,23875
9,0,?,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.4,7.0,160,5500,16,22,?

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized-losses  205 non-null    object
 2   make               205 non-null    object
 3   fuel-type          205 non-null    object
 4   aspiration         205 non-null    object
 5   num-of-doors       205 non-null    object
 6   body-style         205 non-null    object
 7   drive-wheels       205 non-null    object
 8   engine-location    205 non-null    object
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64
 14  engine-type        205 non-null    object
 15  num-of-cylinders   205 non-null    object
 16  engine-size        205 non-null    int64
 17  fuel-system        205 non-null    object
 18  bore               205 non-null    object
 19  stroke             205 non-null    object
 20  compression-ratio  205 non-null    float64
 21  horsepower         205 non-null    object
 22  peak-rpm           205 non-null    object
 23  city-mpg           205 non-null    int64
 24  highway-mpg        205 non-null    int64
 25  price              205 non-null    object
dtypes: float64(5), int64(5), object(16)
memory usage: 41.8+ KB

In [ ]:
list(data.columns)

['symboling',
 'normalized-losses',
 'make',
 'fuel-type',
 'aspiration',
 'num-of-doors',
 'body-style',
 'drive-wheels',
 'engine-location',
 'wheel-base',
 'length',
 'width',
 'height',
 'curb-weight',
 'engine-type',
 'num-of-cylinders',
 'engine-size',
 'fuel-system',
 'bore',
 'stroke',
 'compression-ratio',
 'horsepower',
 'peak-rpm',
 'city-mpg',
 'highway-mpg',
 'price']

In [ ]:
data.duplicated().sum()

0

In [ ]:
data.shape

(205, 26)

In [ ]:
data.isnull().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
aspiration           0
num-of-doors         0
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 0
stroke               0
compression-ratio    0
horsepower           0
peak-rpm             0
city-mpg             0
highway-mpg          0
price                0
dtype: int64

In [ ]:
data.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450

In [ ]:
data.replace('?', np.nan, inplace =True)

In [ ]:
data.isnull().sum()

symboling             0
normalized-losses    41
make                  0
fuel-type             0
aspiration            0
num-of-doors          2
body-style            0
drive-wheels          0
engine-location       0
wheel-base            0
length                0
width                 0
height                0
curb-weight           0
engine-type           0
num-of-cylinders      0
engine-size           0
fuel-system           0
bore                  4
stroke                4
compression-ratio     0
horsepower            2
peak-rpm              2
city-mpg              0
highway-mpg           0
price                 4
dtype: int64

In [ ]:
'''
data['price'] = data['price'].apply(float)
data['peak-rpm'] = data['peak-rpm'].apply(float)
data['horsepower'] = data['horsepower'].apply(float)
'''

data['price'] = data['price'].astype(float)
data['peak-rpm'] = data['peak-rpm'].astype(float)
data['horsepower'] = data['horsepower'].astype(float)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized-losses  164 non-null    object
 2   make               205 non-null    object
 3   fuel-type          205 non-null    object
 4   aspiration         205 non-null    object
 5   num-of-doors       203 non-null    object
 6   body-style         205 non-null    object
 7   drive-wheels       205 non-null    object
 8   engine-location    205 non-null    object
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64
 14  engine-type        205 non-null    object
 15  num-of-cylinders   205 non-null    object
 16  engine-size        205 non-null    int64
 17  fuel-system        205 non-null    object
 18  bore               201 non-null    object
 19  stroke             201 non-null    object
 20  compression-ratio  205 non-null    float64
 21  horsepower         203 non-null    float64
 22  peak-rpm           203 non-null    float64
 23  city-mpg           205 non-null    int64
 24  highway-mpg        205 non-null    int64
 25  price              201 non-null    float64
dtypes: float64(8), int64(5), object(13)
memory usage: 41.8+ KB

In [ ]:
data.head(10)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102.0,5500.0,24,30,13950.0
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.0,115.0,5500.0,18,22,17450.0
5,2,NaN,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.4,8.5,110.0,5500.0,19,25,15250.0
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.4,8.5,110.0,5500.0,19,25,17710.0
7,1,NaN,audi,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.4,8.5,110.0,5500.0,19,25,18920.0
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.4,8.3,140.0,5500.0,17,20,23875.0
9,0,NaN,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.4,7.0,160.0,5500.0,16,22,NaN

In [ ]:
data.nunique()

symboling              6
normalized-losses     51
make                  22
fuel-type              2
aspiration             2
num-of-doors           2
body-style             5
drive-wheels           3
engine-location        2
wheel-base            53
length                75
width                 44
height                49
curb-weight          171
engine-type            7
num-of-cylinders       7
engine-size           44
fuel-system            8
bore                  38
stroke                36
compression-ratio     32
horsepower            59
peak-rpm              23
city-mpg              29
highway-mpg           30
price                186
dtype: int64

In [ ]:
print('Fuel Types   : ',data['fuel-type'].unique())
print('Body Styles  : ',data['body-style'].unique())
print('Drive Wheels : ',data['drive-wheels'].unique())
print('Fuel System  : ',data['fuel-system'].unique())
print('Engine Type  : ',data['engine-type'].unique())

Fuel Types   :  ['gas' 'diesel']
Body Styles  :  ['convertible' 'hatchback' 'sedan' 'wagon' 'hardtop']
Drive Wheels :  ['rwd' 'fwd' '4wd']
Fuel System  :  ['mpfi' '2bbl' 'mfi' '1bbl' 'spfi' '4bbl' 'idi' 'spdi']
Engine Type  :  ['dohc' 'ohcv' 'ohc' 'l' 'rotor' 'ohcf' 'dohcv']

In [ ]:
data['city-mpg'].mean()

25.21951219512195

In [ ]:
data.groupby(by = 'fuel-type')['city-mpg'].mean()

fuel-type
diesel    30.30000
gas       24.67027
Name: city-mpg, dtype: float64

In [ ]:
data['body-style'].value_counts()

body-style
sedan          96
hatchback      70
wagon          25
hardtop         8
convertible     6
Name: count, dtype: int64

In [ ]:
data['fuel-type'].value_counts(normalize = True)

fuel-type
gas       0.902439
diesel    0.097561
Name: proportion, dtype: float64

In [ ]:
data.groupby(by = 'body-style')['highway-mpg'].mean()

body-style
convertible    26.000000
hardtop        27.250000
hatchback      32.171429
sedan          30.833333
wagon          28.720000
Name: highway-mpg, dtype: float64

In [ ]:
data.groupby('body-style')['highway-mpg'].mean().sort_values(ascending = False)

body-style
hatchback      32.171429
sedan          30.833333
wagon          28.720000
hardtop        27.250000
convertible    26.000000
Name: highway-mpg, dtype: float64

In [ ]:
data.groupby(by = 'aspiration')['highway-mpg'].mean().sort_values()

aspiration
turbo    27.027027
std      31.571429
Name: highway-mpg, dtype: float64

In [ ]:
data.groupby(by = 'aspiration')['city-mpg'].mean().sort_values(ascending = False)

aspiration
std      25.839286
turbo    22.405405
Name: city-mpg, dtype: float64

In [ ]:
data.groupby(by = ['body-style','fuel-type'])['city-mpg'].mean()

body-style   fuel-type
convertible  gas          20.500000
hardtop      diesel       22.000000
             gas          21.571429
hatchback    diesel       38.000000
             gas          26.144928
sedan        diesel       31.600000
             gas          24.160494
wagon        diesel       24.000000
             gas          24.045455
Name: city-mpg, dtype: float64

In [ ]:
data.groupby(by = ['aspiration','fuel-type'])['city-mpg'].mean()

aspiration  fuel-type
std         diesel       36.857143
            gas          25.360248
turbo       diesel       26.769231
            gas          20.041667
Name: city-mpg, dtype: float64

In [ ]:
data.groupby(by = ['fuel-type','aspiration'])['city-mpg'].mean()

fuel-type  aspiration
diesel     std           36.857143
           turbo         26.769231
gas        std           25.360248
           turbo         20.041667
Name: city-mpg, dtype: float64

In [ ]:
data['comb_mpg'] = (data['city-mpg'] + data['highway-mpg'])/2
data.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,comb_mpg
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0,24.0
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0,24.0
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0,22.5
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,mpfi,3.19,3.4,10.0,102.0,5500.0,24,30,13950.0,27.0
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,mpfi,3.19,3.4,8.0,115.0,5500.0,18,22,17450.0,20.0

Need to add agenda and Key takeaways:

Agenda can be at timestamp 00:00:16 (Before the transition to Notebook page and previous lecture recap).

Key takeaways can be fitted at timestamp 00:53:06 (Before Outro)

Agenda :
- Pandas Recap
  - Series, Dataframe
- Important Dataframe Functions
- Working with CSV Files

Key Takeaways :
- Important Dataframe Functions
  - View, Update Data
  - Missing Values & Duplicates
  - Descriptive Statistics
  - Grouping and Aggregate Functions
  - Custom Functions

- Working with CSV Files
  - Load, View, & explore data
  - Transformations and Analysis